// Code generated by sqlc. DO NOT EDIT.
package sqlc

import "context"

const getUser = "SELECT id, name, email\nFROM users\nWHERE id = ?\nLIMIT 1"

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
